### ISSUE TITLE
PAYJPのシークレットキーを.envで管理できるようにする。

### ISSUE THREAD

**Issue by KoichiOzaki** [NobutakaX/etsy-project#16]
`items_controller.rb `
`puchaseメソッド`
のシークレットキーを都度ローカルで書き換えないと行けない。
AWSのシークレットキーと同じように `.env` を使用して管理しましょう！

**Comment by KoichiOzaki** [comment]
後、一点質問なのですがPAYJPって管理画面みたいなのってあります？
決済データを見える画面とか。

**Comment by NobutakaX** [comment]
管理画面あります！必要ならアクセス情報を共有します．
https://id.pay.jp/me

**Comment by NobutakaX** [comment]
おっとスミマセン．#16のローカルへの落とし込みがわからず新規作成してしまいました．
https://github.com/NobutakaX/etsy-project/pull/18

**Comment by KoichiOzaki** [comment]
これはissueなのでローカルへ落とすことはできないです。
issue機能っていうGithubの機能で、懸案・問題リストを登録し管理する機能があります。

**Comment by KoichiOzaki** [comment]
一旦アカウントの共有はいらないです！
管理画面で決済データの確認できそうなら大丈夫です！

**Comment by NobutakaX** [comment]
ありがとうございます．Issue機能について，以下の記事を確認しました．https://seleck.cc/647
